name: Spustit denní kontrolu cen

on:
  schedule:
    - cron: '0 5 * * *'  # každý den v 6:00 UTC = 8:00 SEČ
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalace závislostí
        run: pip install -r requirements.txt

      - name: Spuštění skriptu
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
